### PR TITLE
update api definition files

### PR DESCRIPTION
**Pull request by bearmini**
This commit takes in the following updates to the API definition files:

- add operator configuration APIs
- avoid specifying charset=UTF-8 on application/json
- fix x-soracom-cli issues
- improve english descriptions

### CODE REVIEW

**Comment by makoto-soracom** [comment]
おぉ、すごく光栄なのですが、荷が勝っている感じがします。どのあたりを確認すればいいでしょう～。yaml ファイルが soracom-api と同じかどうかくらいしか自信をもって確認できそうにないでしてｗ

**Comment by moznion** [comment]
@bearmini I have some questions:

- Why did you remove the charset specifier from the content-type header? What is the motivation?
- What kind of the x-soracom-cli issues did you fix?

**Comment by bearmini** [comment]
Good points.

Regarding `charset`, specifying any parameters (including `charset`) to `application/json` media type is unnecessary (or, undefined). In the RFC 8259, 11 IANA Considerations:

>    Required parameters:  n/a
>
>    Optional parameters:  n/a
>  ...
>    Note:  No "charset" parameter is defined for this registration.
>      Adding one really has no effect on compliant recipients.

There was a mix of those with and without the charset parameter, so I wanted to unify those without.

Regarding `x-soracom-cli` issues, we fixed the following issues:
- Some APIs simply do not have `x-soracom-cli` entry. Therefore the APIs cannot be called using soracom-cli.
  - `lora-network-sets put-tag`
  - `orders resource-initial-setting update`
- `/stats/harvest/operators/{operator_id}` and `/stats/harvest/subscribers/{imsi}` have the same `x-soracom-cli` entry `stats harvest get` which causes the problem that only one of them can be called via soracom-cli. We gave different names for each command i.e. `stats harvest operators get` and `stats harvest subscribers get` respectively. We researched the change might cause a breaking issue to our existing customer, but we found that no customers called the APIs via soracom-cli for some period of time. So we decided to make the change.

**Comment by 0x6b** [comment]
@bearmini Thanks much for the PR! Reviewed the changes and it looks good to me.

I found the PR includes additional improvements on top of your description i.e.

- `sims create-arc-session` now accepts empty request body.
- `#/components/schemas/Cell/properties/radioType/enum` has new enum as `3G`, `GSM`, `LTE`, `LTE-M`, `NB-IoT`.

It would make it easier for us reviewers to review the changes and its background, if we have `links` to PRs in our internal repository. Do you think this is possible, even if it may be difficult in some cases?

**Comment by 0x6b** [comment]
We decided not to discuss any relevant internal PRs here after discussing it...internally.

**Review by moznion — APPROVED** [review]
@bearmini Thank you for describing out it. Totally, I understand the background and the actual changes. Looks fine.

**Pull request merged**
