### PR TITLE
output just text instead of go-syntax rep of the value

### PR DESCRIPTION
**Pull request by 0x6b**
I found that with current `--query` implementation (#36), say running `soracom subscribers get --imsi xxx --query '.sessionStatus'` will output the result as:

```go
map[string]interface {}{"dnsServers":interface {}(nil), "imei":interface {}(nil), "lastUpdatedAt":1.628168770317e+12, "location":interface {}(nil), "online":false, "ueIpAddress":interface {}(nil)}
```

instead of:

```json
{
  "dnsServers": null,
  "imei": null,
  "lastUpdatedAt": 1628168770317,
  "location": null,
  "online": false,
  "ueIpAddress": null
}
```

Similar cases:

| command            | query                            | actual                                 | expected                 |
| ------------------ | -------------------------------- | -------------------------------------- | ------------------------ |
| `subscribers get`  | `.sessionStatus.dnsServers`      | `<nil>`                                | (blank)                  |
| `subscribers get`  | `.[] \| {imsi: .imsi, speedClass: .type}` | `map[string]interface {}{"imsi":"aaaaaaaaaaaaaaa", "speedClass":"s1.standard"}`           | `{"imsi":"aaaaaaaaaaaaaaa","speedClass":"s1.standard"}`            |
| `subscribers list` | `.[] \| [.imsi, .plan]`          | `[]interface {}{"aaaaaaaaaaaaaaa", 0}` | `["aaaaaaaaaaaaaaa", 0]` |

This PR will improve output, with shamelessly referring https://github.com/cli/cli/blob/trunk/pkg/export/filter.go so please reivew. Thanks!

### CODE REVIEW

**Comment by bearmini** [comment]
Oh good catch. No body wants Golang syntax output :rofl:

**Comment by bearmini** [comment]
Hmm, this seems not expected result :thinking: 
```
$ soracom subscribers list --query '.[] | [.imsi, .plan] | @csv'
"440103029690713",0"440103054644785",0"440103089554095",0"440103213229323",0"440103227422144",0"440512050423513",1"440525060010513",0"440525060030864",0
```

expected result is:
```
$ soracom subscribers list | jq  '.[] | [.imsi, .plan] | @csv'
"\"440103029690713\",0"
"\"440103054644785\",0"
"\"440103089554095\",0"
"\"440103213229323\",0"
"\"440103227422144\",0"
"\"440512050423513\",1"
"\"440525060010513\",0"
"\"440525060030864\",0"
```

**Comment by bearmini** [comment]
We might need the function like this:
https://github.com/itchyny/gojq/blob/955aed36a5508f81f82380fd3333ee042682f1da/cli/encoder.go#L36

**Comment by 0x6b** [comment]
Thank you for pointing out. gojq's implementation looks more robust. I'll look into the situation later.

**Comment by 0x6b** [comment]
@bearmini 
Fixing missing new line (1cd39980e10b5297275d09d852723d8953b967a7) partially solved your point.

```
$ soracom subscribers list --jq '.[] | [.imsi, .plan] | @csv'
"xxxxxxxxxx02511",0
"xxxxxxxxxx12501",0
"xxxxxxxxxx12502",0
...
```

Before move this PR forward, I'd like to confirm that do we have to make output format strictly same as `jq`? For compatiblity with `jq` command, it'd be nice to have same output. But for me not-encoded-as-JSON-string output is convenient for further processing. (I always forget to add `-r` option at first run.)

If we go with compatible output way:

```
$ soracom subscribers list --jq '.[] | [.imsi, .plan] | @csv'
"\"xxxxxxxxxx02511\",0"
...
```

I think we have to implement `--raw-output/-r` option as well.

```
$ soracom subscribers list --jq --raw-output '.[] | [.imsi, .plan] | @csv'
"xxxxxxxxxx02511",0
...
```

**Comment by 0x6b** [comment]
Close this PR since there is no clear demand (at this moment) and the PR is not actively maintained.

**Pull request closed without merging**
