### PR TITLE
update golang version

### PR DESCRIPTION
**Pull request by bearmini**
Go のバージョンを現時点の安定版の最新である 1.17.8 に更新しました

### CODE REVIEW

**Comment by bearmini** [comment]
renovate とか入れたほうがいいのかな

**Review by 0x6b — APPROVED** [review]
LGTM. Thank you!

**Review by moznion — APPROVED** [review]
Looks good.
But I think if we omit the patch version, it uses the latest patched version automatically, isn't it?

**Comment by bearmini** [comment]
Regarding to `build/Dockerfile`, If the patch number was omitted from the `FROM` statement and I had an older image tagged `1.17`, docker did not automatically upgrade the older image to the latest version (if I remember correctly). So I had to explicitly upgrade it to the latest manually to build with the latest image.

For GitHub workflow, it might be true if we specify the version number without patch number, the latest version will be used. But there was a discussion to use explicit version instead of like `^1.17` [here](https://github.com/soracom/soracom-cli/pull/43/files#r733242816).

**Pull request merged**
